// ============================================================
// site-config.js — generated by tools/generate-sites.mjs
// This file is AUTO-GENERATED from site.toml + assets. Do not
// hand-edit it; edit the source data and re-run the generator.
// ============================================================

export default {
  slug: '__SLUG__',
  name: '__NAME__',
  number: '__NUMBER__',
  party: '__PARTY__',
  role: '__ROLE__',
  placeholder: __PLACEHOLDER__,
  tagline: '__TAGLINE__',
  bio: '__BIO__',
  proposals: __PROPOSALS__,
  media: {
    foto: __MEDIA_FOTO__,
    logo: __MEDIA_LOGO__,
    jingle: __MEDIA_JINGLE__
  },
  social: {
    instagram: '__INSTAGRAM__',
    facebook: '__FACEBOOK__',
    whatsapp: '__WHATSAPP__'
  },
  links: {
    clickup: '__CLICKUP_URL__'
  }
}
