// ============================================================
// site-config.js — generated by tools/generate-sites.mjs
// This file is AUTO-GENERATED from site.toml + assets. Do not
// hand-edit it; edit the source data and re-run the generator.
// ============================================================

export default {
  slug: "deputado-08",
  name: "Deputado 08",
  number: "",
  party: "",
  role: "Candidatura",
  placeholder: true,
  tagline: "Juntos por um futuro melhor.",
  bio: "Conheça as ideias e propostas de Deputado 08. Em breve mais informações.",
  proposals: [],
  media: {
    foto: null,
    logo: null,
    jingle: null
  },
  social: {
    instagram: "",
    facebook: "",
    whatsapp: ""
  },
  links: {
    clickup: ""
  }
}
